name: Deploy to DigitalOcean

on:
  push:
    branches: [ development ]  # Se ejecuta cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /var/www/Apps/PampeanoAPI 
          git pull origin development
          npm install
          pm2 restart pampeano-api-development
